server:
  port: 8080

logging:
  level:
    root: INFO
    ca: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          spring-client-oidc:
            provider: spring
            client-id: spring-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: spring-client-oidc
        provider:
          spring:
            issuer-uri: http://auth-server:9000